stages:
  - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    SERVER_TAG: loadapicron-server
    CLIENT_TAG: loadapicron-client
  before_script:
    - echo "hello world"
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY/group/project/$SERVER_TAG:latest ./server
    - docker push $CI_REGISTRY/group/project/$SERVER_TAG:latest
    - docker build --pull -t $CI_REGISTRY/group/project/$CLIENT_TAG:latest ./client
    - docker push $CI_REGISTRY/group/project/$CLIENT_TAG:latest
  #only:
  #  - master