stages:
  - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t loadapicron/server ./server
    - docker push loadapicron/server
    - docker build --pull -t loadapicron/client ./client
    - docker push loadapicron/client
  #only:
  #  - master