stages:
  - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    SERVER_TAG: loadapicron-server
    CLIENT_TAG: loadapicron-client
  before_script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t $SERVER_TAG ./server
    - docker push $SERVER_TAG
    - docker build --pull -t $CLIENT_TAG ./client
    - docker push $CLIENT_TAG
  #only:
  #  - master