version: "3"
services:
  client:
    container_name: react
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    links:
      - app
    networks: 
      - webappnetwork
    stdin_open: true
  app:
    container_name: nodejs
    #restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "49160:8080"
      - "9229:9229" #debug
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    links:
      - mongo
    networks: 
      - webappnetwork
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks: 
      - webappnetwork
volumes: 
  mongodata:
    external: false
networks:
  webappnetwork:
    driver: bridge